feat: set SSL_CERT_FILE and provide a Cmd
tazjin/nixery pull request #147
Opened 2021-12-23 11:31 UTC by jpetazzo

Two minor "quality of life" improvements:
- automatically set SSL_CERT_FILE environment variable,
  so that programs relying on OpenSSL for certificate
  validation can actually validate certificates
  (the certificates are included no matter what since
  we add the "cacert" package to all images)
- if the requested image includes an interactive shell
  (e.g. if it includes the "shell" metapackage), set
  the image Cmd to "bash", which allows to execute
  "docker run nixery.dev/shell" and get a shell)

I'm happy to split this PR in two if you'd like, but
since both features touch the Config structure and are
rather small, I thought it would make sense to bundle
them together.

To give you a bit more context around this PR:
I've been using Nixery extensively in live demos,
teaching environments, etc. and these have been
the two most confusing items for the students
(number 3 is the lack of /tmp, which I'll try to address
in a future PR).

Related: #101 #133

2021-12-24 18:20 UTC, tazjin requested changes

2021-12-24 18:20 UTC, tazjin commented on manifest/manifest.go
> +		Cmd []string `json:"cmd"`
Should this be tagged `omitempty` to avoid serialising empty commands if bash is not included?

2021-12-26 11:08 UTC, jpetazzo commented on manifest/manifest.go
> +		Cmd []string `json:"cmd"`
Excellent idea! I tagged both fields (`Cmd` and `Env`) - we set an env var so `Env` won't be empty anyway, but thought it would be nice for consistency and in case it gets changed later.

2021-12-26 15:39 UTC, tazjin approved these changes

2021-12-27 08:26 UTC, merged

2021-12-27 08:31 UTC, tazjin commented
Thanks! Staged all of these for release to nixery.dev in TVL [cl/4702](https://cl.tvl.fyi/c/depot/+/4702).